### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by srugano** [henningpohl/latex-emoji#1]
Is this package compatible with Linux or reserved to Windows only ?
Can you indicate how it's installed ? thanks.

**Comment by henningpohl** [comment]
Should work on all systems. There isn't really anything specific to some os in there. As for installing: just copy the whole folder into your project. You actually only need emoji.sty and the image folders, though. Try to compile example.tex to see whether it works on your system.

**Comment by pgvoorhees** [comment]
If you want it to be part of your system install, clone the project in to your texmf/tex/latex directory and update your package index by running: 

- teTeX, TeX Live, fpTeX: texhash
- web2c: mktexlsr
- MacTeX: MacTeX appears to do this for you.
- MikTeX: initexmf --update-fndb (or use the GUI)
